spring:
  application:
    name: lm-organizations
  datasource:
    url: jdbc:postgresql://localhost:5433/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: '8091'
app:
  cors:
    allowed-origins: https://cartagenacorporation.com,https://www.cartagenacorporation.com
  jwt:
    secret: ${JWT_SECRET}
role:
  service:
    url: http://localhost:8085/api/roles
config:
  service:
    url: http://localhost:8088/api/config